# Continous Integration setup for SU2.
# Tests on the develop branch in both serial and parallel.

dist: trusty
sudo: required

language: python

compiler:
    - gcc

notifications:
    email:
        recipients:
            - clarkp@utexas.edu
  
branches:
    only:
        - pecos-dev
        - pecos-improve-unit-tests

python:
    # TODO: Re-include python 3 after testing is complete
    - 2.7

matrix:
  include:
    - env:
        # Serial build and test
        - CONFIGURE_COMMAND="./preconfigure.py --prefix=$TRAVIS_BUILD_DIR --enable-PY_WRAPPER --disable-tecio"
          TEST_SCRIPT=serial_regression.py
    - env:
        # Parallel build and test
        - CONFIGURE_COMMAND="./preconfigure.py --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR --enable-PY_WRAPPER --disable-tecio"
          TEST_SCRIPT=parallel_regression.py
    - env:
        # Serial build and test for AD
        - CONFIGURE_COMMAND="./preconfigure.py --with-cc=gcc --with-cxx=g++ --prefix=$TRAVIS_BUILD_DIR --enable-autodiff --enable-direct-diff --disable-tecio"
          TEST_SCRIPT=serial_regression_AD.py
    - env:
        # Serial build and unit-test
        - CONFIGURE_COMMAND="./preconfigure.py --prefix=$TRAVIS_BUILD_DIR --disable-tecio --with-Boost-include=/usr/include/"
          TEST_SCRIPT=serial_regression.py
      addons:
          apt:
              sources: ['boost-latest']
      after_success:
        - make check -j 4
    - env:
        # Parallel build and unit-test
        - CONFIGURE_COMMAND="./preconfigure.py --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR --disable-tecio --with-Boost-include=/usr/include/"
          TEST_SCRIPT=parallel_regression.py
      addons:
          apt:
              sources: ['boost-latest']
      after_success:
        - make check -j 4


env:
    global:
        CXXFLAGS="-O0 -Wall -Wextra -Wno-unused-parameter -Wno-empty-body -Wno-format-security"

before_install:
    # Temporarily fixes Travis CI issue with paths for Python packages
    - export PATH=/usr/bin:$PATH

    # Install the necessary packages using apt-get with sudo
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential libopenmpi-dev
 
    # Install Python dependencies
    # http://conda.pydata.org/docs/travis.html#the-travis-yml-file
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda install -q python=$TRAVIS_PYTHON_VERSION numpy scipy mpi4py swig

    # to avoid interference with MPI
    - test -n $CC  && unset CC
    - test -n $CXX && unset CXX

install:
    # Configure, make, and install SU2
    - echo $TRAVIS_BUILD_DIR
    - echo $CONFIGURE_COMMAND
    - ./bootstrap
    - $CONFIGURE_COMMAND
    - make -j 4
    - make install

    # Add environmental variables according to the configure step
    - export SU2_RUN=$TRAVIS_BUILD_DIR/bin
    - export SU2_HOME=$TRAVIS_BUILD_DIR
    - export PATH=$PATH:$SU2_RUN
    - export PYTHONPATH=$PYTHONPATH:$SU2_RUN

before_script:
    # Get the test cases
    - git clone -b v6.0.1 https://github.com/su2code/TestCases.git ./TestData
    - cp -R ./TestData/* ./TestCases/

    # Enter the SU2/TestCases/ directory, which is now ready to run
    - cd TestCases/

script:
    cd ./
