# Continous Integration setup for SU2.
# Tests on the develop branch in both serial and parallel.

dist: xenial
sudo: required

language: c++

cache: 
    - ccache
    - pip
    - directories: 
      - $HOME/.pyenv_cache

compiler:
    - gcc

notifications:
    email:
        recipients:
            - clarkp@utexas.edu

branches:
    only:
        - pecos-dev
        - meson-build-system

virtualenv:
  system_site_packages: true

matrix:
  include:
    - env:
        # Serial build and test
        - CONFIGURE_COMMAND="./meson.py build --prefix=$TRAVIS_BUILD_DIR -Denable-pywrapper=true -Dwith-mpi=disabled"
          TEST_SCRIPT=serial_regression.py
    - env:
        # Parallel build and test
        - CONFIGURE_COMMAND="./meson.py build --prefix=$TRAVIS_BUILD_DIR -Denable-pywrapper=true"
          TEST_SCRIPT=parallel_regression.py

before_install:
    # Temporarily fixes Travis CI issue with paths for Python packages
    - export PATH=/usr/bin:$PATH
    - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
    # Install the necessary packages using apt-get with sudo
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential python3-numpy python3-scipy libopenmpi-dev openmpi-bin swig python3-mpi4py  
    # to avoid interference with MPI
    - test -n $CC  && unset CC
    - test -n $CXX && unset CXX

install:
    # build ninja
    - echo $CONFIGURE_COMMAND
    - $CONFIGURE_COMMAND
    - ./meson.py build --reconfigure --optimization=2
    - ./meson.py build --reconfigure --warnlevel=2
    - ./ninja -C build install

    # Add environmental variables according to the configure step
    - export SU2_RUN=$TRAVIS_BUILD_DIR/bin
    - export SU2_HOME=$TRAVIS_BUILD_DIR
    - export PATH=$PATH:$SU2_RUN
    - export PYTHONPATH=$PYTHONPATH:$SU2_RUN

before_script:
    # Get the test cases
    - git clone -b v6.0.1 https://github.com/pecos-hybrid/TestCases.git ./TestData
    - cp -R ./TestData/* ./TestCases/
    
    # Enter the SU2/TestCases/ directory, which is now ready to run
    - cd TestCases/

script:
    # Run the tests via the Python scripts
    - python $TEST_SCRIPT
